"""Add is_admin to User model

Revision ID: 90434b443e5c
Revises: 
Create Date: 2026-08-20 18:37:27.444657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90434b443e5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
