"""Add stock column to products and create order_items table

Revision ID: fb091e242c91
Revises: 1ccd9a66cdc8
Create Date: 2026-08-21 11:31:54.564834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb091e242c91'
down_revision = '1ccd9a66cdc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('stock')

    # ### end Alembic commands ###
